config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

   resources :users do
    member do
      get :followings, :followers
    end
  end
  
  #これにより作られるルーティングは?  get(verb)  users/1/following  following_user_path(1) 
  
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    belongs_to :user  #1つだけのユーザーに紐づく 多 対 1の関係
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }    
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end


#クラスのオブジェクトなのでclass_name Userつける

app/models/user.rb
class User < ActiveRecord::Base
     before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :hobby, presence: true, length: { maximum: 50 }, on: :update
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
    def logged_in_user
      unless logged_in?
       store_location
       flash[:danger] = "Please log in."
       redirect_to login_url
      end
    end
end


     #インデントはスペース２回の（2）!鉄則

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create]  #アクション前にapplication controllerのloggedinメソッドを実行 クリエイトの時だけね
    
    def create
      @micropost = current_user.microposts.build(microposts_params)  #常に後ろから読むイメージ 
      if @micropost.save                                            #マイクロポストのパラーメーターを受け取る
      flash[:success] = "Micropost created!"                         #現在のユーザーに紐付け
      redirect_to root_url                                           #インスタンス変数へ入れる
      else
       @feed_items = current.feed_items.includes(:user).order(created_at: :desc)
       render 'static_pages/home'
      end
    end
    
    def destroy
      @micropost = current_user.microposts.find_by(id: params[:id]) #ユーザーID＆ポストID
      return redirect_to root_url if @micropost.nil? #自分のでなければroot行き！！
      @micropost.destroy
      flash[:success] = "マイクロポストを削除しました"
      redirect_to request.referrer || root_url
    end

    
    private
    
    def microposts_params  
        params.require(:micropost).permit(:content)
    end
end

    

#paramsメソッドで、マイクポストのコンテンツを安全に受け取る

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
before_action :logged_in_user

  def create #フォローするユーザーのidを受取 そのidユーザーを引数にしてuses_controlerのfollowメソッドを実行している
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy  #ログインアカウントのリレイションを確認 フォローしている対象を引数にして、users controllerのunfollowメソッドを実行
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
  

  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)  
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end

  def destroy    #ログアウト処理
    session[:user_id] = nil    #セッション破棄
    redirect_to root_path
  end
end




#params[:session]部分にloginフォームに入力したパラメータが入っている
#1行目で入力emailを元にユーザーを検索 2行目でパスワードが一致しているかを確認
#

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def home
     if logged_in?
     @micropost = current_user.microposts.build  #build=newだが buildはuser_idが紐づく
     @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
     end
   end
end

#includes(:user) →→つぶやきのユーザー情報をプリロード処理するためのメソッド

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only:[:edit, :update]
  before_action :correct_user, only:[:edit, :update]
  
  
  def show # 追加
   @user = User.find(params[:id])
  end
  
  def new
    @user = User.new   #モデルは大文字
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
    def edit
    end
  
  
  def update   #attribute 更新メソッド 更新されたら userページへ飛ばす　ダメならeditページへそのまま
    @user = User.find_by_id(params[:id]) 
    if @user.update_attributes(user_params)
      redirect_to @user
      flash[:success] = "プロフィールの更新が完了しました"
      else
      render 'edit'
    end
  end
  
    private   #簡単にはアクセス出来ないようにしたいものはprivateより下に記載
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :age, :region, :sex, :hobby)
    end
    
    def logged_in_user  #ログイン済みかどうか?? アクセス簡易のプロテクトはprivate以下に記載 まわりから見えないように！
      unless logged_in?
        flash[:danger] = "まずはログインしてください"
        redirect_to login_url
      end
    end
    
      def correct_user
        @user = User.find(params[:id])
        unless @user == current_user
        redirect_to(root_url)   
        flash[:danger] = "そのページへのアクセスは許可されていません!"
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||=User.find_by(id: session[:user_id])
    end
    
    def logged_in?
      !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end


# ||=左の値がfalse or nilなら右の値の代入を実施する
#find by メソッド ：引数で見つける 見つからない場合はnil返す

#logged in メソッド  !!否定演算子を２回使用したもの　 右側に続く値が存在する場合はfolse !!で反転してtrue
#ログインが必要な画面にアクセスしようとした場合にログイン画面に一度飛ばす。よくある機能 

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class ="navbar navbar-fixed-top navbar-inverse">
  <div class = "container">
      <%= link_to "Microposts", root_path, id: "logo" %>
      <nav>
          <ul class ="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help" ,   '#' %></li>
              <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li><class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>  
  
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
 </head>
 <body>
  <%= render 'layouts/header' %>
   <div class="container">
     <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> 
    <%= yield %>
   </div>
 </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,           
                                    data: {confirm: "Are you sure?"} %>
    <% end %>
  </span>
</li>

<!-- micropostの引数だけで削除URLのpathが作成されるのはresouces:micropostsを書き込んでいるから 便利ね〜 -->
     <!--マイクロポストポストの一覧表示を行なうファイル-->

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

     <!--クリエイトとデストロイでは画面の一部を書き換えるjsファイルを作る必要がある やってることはビューの置き換え-->
     <!--フォロー後→アンフォローフォームにビューを置き換え-->
     
    

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");


     <!--アンフォロー後のビューの置き換え→フォローフォームへ-->

app/views/shared/_error_messages.html.erb
<% if object.errors.any?%>
 <div id="error_explanation">
  <div class='alert alert-danger'>
    The form contains <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
 </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>

  <ol class="microposts">
    
<%= render @feed_items %>

  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Copose new micropost..."%>
    </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>


     <!--placeholder: OOOOは　記入欄に仮の文字列を表示！-->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= followings_user_path(@user) %>">
    <strong id="followings" class="stat">
      <%= @user.following_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.follower_users.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<%= current_user.name %>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        
        <%= render 'shared/user_info' %>
        
      </section>
      
       <section class="microposts_form">
         
        <%= render 'shared/micropost_form' %>
        
      </section>
    </aside>
    
    <div class="col-md-8">
    <h3>Micropost Feed</h3>
    
    <%= render 'shared/feed' %>
    
    
    </div>
  </div>
  
<% else %>

  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user,size:50 %>
  <span class="user"><%= link_to user.name,user %></span>
  <span class="content">&nbsp;</span>
  <span class="timestamp">&nbsp;</span>
</li>



     <!--nbspノーブレイクスペース　改行なしの空白-->
     
<!--そう言えばここってなんで単数形のuserなんですか?? @usersなのかと思いました-->

app/views/users/_users.html.erb
<li>
  <%= gravatar_for user,size:50 %>
  <span class="user"><%= link_to user.name,user %></span>
  <span class="content">&nbsp;</span>
  <span class="timestamp">&nbsp;</span>
</li>

app/views/users/edit.html.erb
<h1>Edit Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %> <!--エラーメッセージ-->
     
   
   <%= f.label :new_name %>
   <%= f.text_field :name, class: 'form-control' %>
   
   <%= f.label :new_email %>
   <%= f.text_field :email, class: 'form-control' %>
   
   <%= f.label :new_password %>
   <%= f.password_field :password, class: 'form-control' %>
   
   <%= f.label :new_password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation, class: 'form-control' %>
   
   <h1>個人プロフィール編集</h1>
   
   <%= f.label :"年齢" %>
   <%= f.text_field :age, class: 'form-control' %>
   
   <%= f.label :"お住いの地域" %>
   <%= f.text_field :region, class: 'form-control' %>
   
   <%= f.label :"性別" %>
   <%= f.text_field :sex, class: 'form-control' %>
   
   <%= f.label :"趣味" %>
   <%= f.text_field :hobby, class: 'form-control' %>
   
   
   <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
  <% end %>
 </div>
</div>

app/views/users/index.html.erb
<!--Users画面-->

<dv class="row">
  <div class ="col-md-4" >
    <%= gravatar_for(current_user, size:50) %>
    <%= current_user.name %>
  </div>
  <div class ="col-md-8" >
    <ol class = "users">
      <%= render @users %>
    </ol>
  </div>
  <%= paginate @users %>
</div>
 
  


     <!---->
     <!---変数userはなんでも良いいかもそれにおうじて変更！！->

app/views/users/new.html.erb
<h1>Sign in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %> <!--エラーメッセージ-->
     
   
   <%= f.label :name %>
   <%= f.text_field :name, class: 'form-control' %>
   
   <%= f.label :email %>
   <%= f.text_field :email, class: 'form-control' %>
   
   <%= f.label :password %>
   <%= f.password_field :password, class: 'form-control' %>
   
   <%= f.label :password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation, class: 'form-control' %>
   
   <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  <% end %>
 </div>
</div>

app/views/users/show.html.erb
    <!--Profile画面-->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
      <section>
      <%= render 'shared/stats' %>
      </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %> <!--フォロー用のフォームを搭載 フォローアンフォロー切り替えは２つのレンダーで-->
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">           <!--スタイルシートを適用する場合、OOclass = ".OO"かこむ-->
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>

app/views/users/show_favorite.html.erb
<% provide(:title, @title) %>       <!--タイトルにクリックした方を代入-->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
        <h1><%= @user.name %></h1>
        <span><%= link_to "view my profile", @user %></span>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
    </section>
  </aside>
    <div class="col-md-8">
      <h3><%= @title %></h3>
    <% if @users.any? %>
      <ol class="users">
        <%= render @favorite %>        <!--フォロワーかフォローしている人の表示なので`usesの方-->
      </ol>
    <% end %>
  </div>
</div>
        

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>       <!--タイトルにクリックした方を代入-->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
        <h1><%= @user.name %></h1>
        <span><%= link_to "view my profile", @user %></span>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
    </section>
  </aside>
    <div class="col-md-8">
      <h3><%= @title %></h3>
    <% if @users.any? %>
      <ol class="users">
        <%= render @users %>        <!--フォロワーかフォローしている人の表示なので`usesの方-->
      </ol>
    <% end %>
  </div>
</div>
        